"""create social_accounts table

Revision ID: 5b6eedd3612a
Revises: 2ce891a0fe1f
Create Date: 2026-07-31 20:30:02.490338

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5b6eedd3612a'
down_revision: str | None = '2ce891a0fe1f'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('telegram', 'instagram', name='social_platform'), nullable=False),
    sa.Column('external_account_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('encrypted_access_token', sa.String(length=1024), nullable=False),
    sa.Column('encrypted_refresh_token', sa.String(length=1024), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform', 'external_account_id', name='uq_social_account')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_accounts')
    # ### end Alembic commands ###
    # create_table auto-creates the enum type but drop_table does not
    # auto-drop it (asymmetric on the Postgres dialect) -- drop it
    # explicitly so upgrade/downgrade/upgrade stays idempotent.
    sa.Enum(name='social_platform').drop(op.get_bind())
