"""create posts table

Revision ID: 6bc791e28a44
Revises: 8fc915e52133
Create Date: 2026-07-31 21:24:20.026225

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6bc791e28a44'
down_revision: str | None = '8fc915e52133'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('social_account_id', sa.UUID(), nullable=False),
    sa.Column('generation_job_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.String(length=4096), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'publishing', 'published', 'failed', name='post_status'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_message_id', sa.String(length=255), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
    # create_table auto-creates this enum type but drop_table does not
    # auto-drop it -- see the same fix in earlier migrations.
    sa.Enum(name='post_status').drop(op.get_bind())
