"""add image_url to posts

Revision ID: 78dca0802cae
Revises: 6bc791e28a44
Create Date: 2026-07-31 21:35:57.950440

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '78dca0802cae'
down_revision: str | None = '6bc791e28a44'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image_url')
    # ### end Alembic commands ###
