"""create generation_jobs table

Revision ID: 8fc915e52133
Revises: feb8a2c906e0
Create Date: 2026-07-31 20:43:08.050542

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8fc915e52133'
down_revision: str | None = 'feb8a2c906e0'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.Enum('text', 'image', 'video', name='generation_content_type'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'completed', 'failed', 'flagged', name='generation_status'), nullable=False),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generation_jobs')
    # ### end Alembic commands ###
    # create_table auto-creates these enum types but drop_table does not
    # auto-drop them -- see the same fix in earlier migrations.
    sa.Enum(name='generation_status').drop(op.get_bind())
    sa.Enum(name='generation_content_type').drop(op.get_bind())
