"""add video_url to posts

Revision ID: e71eff5e2e59
Revises: 6f723a1be96c
Create Date: 2026-08-05 00:00:00.000000

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e71eff5e2e59'
down_revision: str | None = '6f723a1be96c'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('video_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'video_url')
    # ### end Alembic commands ###
