"""create subscriptions and usage_events tables

Revision ID: feb8a2c906e0
Revises: 5b6eedd3612a
Create Date: 2026-07-31 20:35:56.201422

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'feb8a2c906e0'
down_revision: str | None = '5b6eedd3612a'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Enum('free', 'pro', name='subscription_tier'), nullable=False),
    sa.Column('status', sa.Enum('active', 'past_due', 'canceled', name='subscription_status'), nullable=False),
    sa.Column('store', sa.Enum('none', 'google_play', 'app_store', name='subscription_store'), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('usage_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('generation', 'publication', name='usage_event_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_events_created_at'), 'usage_events', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_events_created_at'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
    # create_table auto-creates these enum types but drop_table does not
    # auto-drop them -- see the same fix in 2ce891a0fe1f/5b6eedd3612a.
    sa.Enum(name='usage_event_type').drop(op.get_bind())
    sa.Enum(name='subscription_store').drop(op.get_bind())
    sa.Enum(name='subscription_status').drop(op.get_bind())
    sa.Enum(name='subscription_tier').drop(op.get_bind())
